apps/lekker_class1/config/routes.rb
Rails.application.routes.draw do
  resources :places 

end

apps/lekker_class1/app/models/place.rb
class Place < ActiveRecord::Base
	validates :name, :address, presence: true
	validates :name, length: { minimum: 4, maximum: 20 }
	has_many :comments
end

apps/lekker_class1/app/controllers/places_controller.rb
class PlacesController < ApplicationController
	def index
		@places = Place.all.order(:name)
	end

	def show
		@place = Place.find params[:id]
	end

	def new
		@place = Place.new
	end
	def create
		@place = Place.new(place_params)

		if @place.save
			redirect_to @place
		else
			render :new
		end
	end

	def edit
	@place = Place.find(params[:id])
	end

	def update
		@place = Place.find(params[:id])

		if @place.update place_params
			redirect_to @place
		else
			render :edit
		end
	end

	def destroy
		@place = Place.find(params[:id])

		@place.destroy
		redirect_to places_path
	end

private
	
	def place_params
		params.require(:place).permit(:name, :description, :address)
	end

end

apps/lekker_class1/app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html>
<head>
  <title>LekkerClass1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= yield %>

</body>
</html>

apps/lekker_class1/app/views/places/_form.html.erb
<%= form_for @place do |f| %>

<% if @place.errors.any? %>
<h2> 
<%= pluralize(@place.errors.count, "error") %>
prohibited this place from being saved
</h2>
<ul>
<% @place.errors.full_messages.each do |msg| %>
<li> <%= msg %> </li>
<% end %>

</ul>
<% end %>

<p><%= f.label :name %>
<%= f.text_field :name %></p>

<p><%= f.label :description %>
<%= f.text_area :description %></p>

<p><%= f.label :address %>
<%= f.text_field :address %></p>

<p><%= f.submit %></p>

<% end %>

apps/lekker_class1/app/views/places/edit.html.erb
<h1> Edit Form </h1>

<%= render 'form' %>

apps/lekker_class1/app/views/places/index.html.erb
<h1> Places Page </h1>
<%= link_to 'Create New Place', new_place_path %>

<% @places.each do |place| %>
	<div>
	<strong><%= link_to place.name, place_path(place) %> </strong>
	
	<p><%= link_to 'Edit', edit_place_path(place) %> </p>

	<p><%= button_to 'Destroy', place_path(place), method: :delete, data: {confirm: "This place sucks."} %> </p>
	</div>
<% end %>

apps/lekker_class1/app/views/places/new.html.erb
<%= form_for @place do |f| %>

<% if @place.errors.any? %>
<h2> 
<%= pluralize(@place.errors.count, "error") %>
prohibited this place from being saved
</h2>
<ul>
<% @place.errors.full_messages.each do |msg| %>
<li> <%= msg %> </li>
<% end %>

</ul>
<% end %>

<p><%= f.label :name %>
<%= f.text_field :name %></p>

<p><%= f.label :description %>
<%= f.text_area :description %></p>

<p><%= f.label :address %>
<%= f.text_field :address %></p>

<p><%= f.submit %></p>

<% end %>

apps/lekker_class1/app/views/places/show.html.erb
<h1> <%= @place.name %> </h1>

<p> <%= @place.description %> </p>
<p> Address: <%= @place.address %> <br> </p>

<%= link_to 'Back', places_path %>